/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../src/components/body/body.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/security';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '@angular/core/src/linker/query_list';
import * as import12 from '../../../../src/components/body/selection.component';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from './selection.component.ngfactory';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '../../../../src/components/body/progress-bar.component';
import * as import17 from './progress-bar.component.ngfactory';
import * as import18 from '../../../../src/components/body/scroller.component';
import * as import19 from '@angular/common/src/directives/ng_for';
import * as import20 from './scroller.component.ngfactory';
import * as import21 from '@angular/core/src/linker/element_ref';
import * as import22 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import23 from '@angular/common/src/directives/ng_style';
import * as import24 from '../../../../src/components/body/body-row-wrapper.component';
import * as import25 from '../../../../src/components/body/body-row.component';
import * as import26 from './body-row-wrapper.component.ngfactory';
import * as import27 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import28 from './body-row.component.ngfactory';
var renderType_DataTableBodyComponent_Host:import0.RenderComponentType = (null as any);
class _View_DataTableBodyComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DataTableBodyComponent_0_4:import3.DataTableBodyComponent;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent_Host0,renderType_DataTableBodyComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('datatable-body',rootSelector,(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable-body');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DataTableBodyComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DataTableBodyComponent_0_4 = new import3.DataTableBodyComponent();
    this._appEl_0.initComponent(this._DataTableBodyComponent_0_4,[],compView_0);
    compView_0.create(this._DataTableBodyComponent_0_4,this.projectableNodes,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.DataTableBodyComponent) && (0 === requestNodeIndex))) { return this._DataTableBodyComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._DataTableBodyComponent_0_4.bodyWidth;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_0) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_0).toString()));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._DataTableBodyComponent_0_4.bodyHeight;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementStyle(this._el_0,'height',((this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_1) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_1).toString()));
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DataTableBodyComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_DataTableBodyComponent_Host === (null as any))) { (renderType_DataTableBodyComponent_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,[],{})); }
  return new _View_DataTableBodyComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DataTableBodyComponentNgFactory:import10.ComponentFactory<import3.DataTableBodyComponent> = new import10.ComponentFactory<import3.DataTableBodyComponent>('datatable-body',viewFactory_DataTableBodyComponent_Host0,import3.DataTableBodyComponent);
const styles_DataTableBodyComponent:any[] = [];
var renderType_DataTableBodyComponent:import0.RenderComponentType = (null as any);
class _View_DataTableBodyComponent0 extends import1.AppView<import3.DataTableBodyComponent> {
  _viewQuery_ScrollerComponent_0:import11.QueryList<any>;
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import2.AppElement;
  _DataTableSelectionComponent_1_4:import12.DataTableSelectionComponent;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import13.NgIf;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import13.NgIf;
  _text_6:any;
  _anchor_7:any;
  /*private*/ _appEl_7:import2.AppElement;
  _TemplateRef_7_5:any;
  _NgIf_7_6:import13.NgIf;
  _text_8:any;
  _text_9:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent0,renderType_DataTableBodyComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_ScrollerComponent_0 = new import11.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'datatable-selection',(null as any));
    this._appEl_1 = new import2.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import14.viewFactory_DataTableSelectionComponent0(this.viewUtils,this.injector(1),this._appEl_1);
    this._DataTableSelectionComponent_1_4 = new import12.DataTableSelectionComponent();
    this._appEl_1.initComponent(this._DataTableSelectionComponent_1_4,[],compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import15.TemplateRef_(this._appEl_3,viewFactory_DataTableBodyComponent1);
    this._NgIf_3_6 = new import13.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_5 = new import2.AppElement(5,1,this,this._anchor_5);
    this._TemplateRef_5_5 = new import15.TemplateRef_(this._appEl_5,viewFactory_DataTableBodyComponent2);
    this._NgIf_5_6 = new import13.NgIf(this._appEl_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    this._anchor_7 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_7 = new import2.AppElement(7,1,this,this._anchor_7);
    this._TemplateRef_7_5 = new import15.TemplateRef_(this._appEl_7,viewFactory_DataTableBodyComponent4);
    this._NgIf_7_6 = new import13.NgIf(this._appEl_7.vcRef,this._TemplateRef_7_5);
    this._text_8 = this.renderer.createText((null as any),'\n    ',(null as any));
      compView_1.create(this._DataTableSelectionComponent_1_4,[[].concat([
        this._text_2,
        this._appEl_3,
        this._text_4,
        this._appEl_5,
        this._text_6,
        this._appEl_7,
        this._text_8
      ]
    )],(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'select',this.eventHandler(this._handle_select_1_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_1,'activate',this.eventHandler(this._handle_activate_1_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    const subscription_0:any = this._DataTableSelectionComponent_1_4.activate.subscribe(this.eventHandler(this._handle_activate_1_1.bind(this)));
    const subscription_1:any = this._DataTableSelectionComponent_1_4.select.subscribe(this.eventHandler(this._handle_select_1_0.bind(this)));
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._anchor_5,
      this._text_6,
      this._anchor_7,
      this._text_8,
      this._text_9
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import13.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import15.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import13.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6; }
    if (((token === import15.TemplateRef) && (7 === requestNodeIndex))) { return this._TemplateRef_7_5; }
    if (((token === import13.NgIf) && (7 === requestNodeIndex))) { return this._NgIf_7_6; }
    if (((token === import12.DataTableSelectionComponent) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._DataTableSelectionComponent_1_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.context.temp;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._DataTableSelectionComponent_1_4.rows = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.context.selected;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._DataTableSelectionComponent_1_4.selected = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.context.selectEnabled;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._DataTableSelectionComponent_1_4.selectEnabled = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.context.selectionType;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._DataTableSelectionComponent_1_4.selectionType = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.rowIdentity;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._DataTableSelectionComponent_1_4.rowIdentity = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.context.selectCheck;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._DataTableSelectionComponent_1_4.selectCheck = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.context.loadingIndicator;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgIf_3_6.ngIf = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = ((this.context.rows == (null as any))? (null as any): this.context.rows.length);
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._NgIf_5_6.ngIf = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:boolean = !((this.context.rows == (null as any))? (null as any): this.context.rows.length);
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._NgIf_7_6.ngIf = currVal_10;
      this._expr_10 = currVal_10;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._viewQuery_ScrollerComponent_0.dirty) {
        this._viewQuery_ScrollerComponent_0.reset([this._appEl_5.mapNestedViews(_View_DataTableBodyComponent2,(nestedView:_View_DataTableBodyComponent2):any => {
          return [nestedView._ScrollerComponent_0_4];
      })]);
      this.context.scroller = this._viewQuery_ScrollerComponent_0.first;
    } }
  }
  private _handle_select_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.select.emit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_activate_1_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.activate.emit($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DataTableBodyComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.DataTableBodyComponent> {
  if ((renderType_DataTableBodyComponent === (null as any))) { (renderType_DataTableBodyComponent = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_DataTableBodyComponent,{})); }
  return new _View_DataTableBodyComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_DataTableBodyComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ProgressBarComponent_0_4:import16.ProgressBarComponent;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent1,renderType_DataTableBodyComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'datatable-progress',(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import17.viewFactory_ProgressBarComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProgressBarComponent_0_4 = new import16.ProgressBarComponent();
    this._appEl_0.initComponent(this._ProgressBarComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_0.create(this._ProgressBarComponent_0_4,[],(null as any));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import16.ProgressBarComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._ProgressBarComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_DataTableBodyComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DataTableBodyComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_DataTableBodyComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ScrollerComponent_0_4:import18.ScrollerComponent;
  _text_1:any;
  _anchor_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _TemplateRef_2_5:any;
  _NgFor_2_6:import19.NgFor;
  _text_3:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent2,renderType_DataTableBodyComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'datatable-scroller',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable-scroll');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import20.viewFactory_ScrollerComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ScrollerComponent_0_4 = new import18.ScrollerComponent(new import21.ElementRef(this._el_0),this.renderer);
    this._appEl_0.initComponent(this._ScrollerComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._anchor_2 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_2 = new import2.AppElement(2,0,this,this._anchor_2);
    this._TemplateRef_2_5 = new import15.TemplateRef_(this._appEl_2,viewFactory_DataTableBodyComponent3);
    this._NgFor_2_6 = new import19.NgFor(this._appEl_2.vcRef,this._TemplateRef_2_5,this.parent.parentInjector.get(import22.IterableDiffers),this.parent.ref);
    this._text_3 = this.renderer.createText((null as any),'\n      ',(null as any));
      compView_0.create(this._ScrollerComponent_0_4,[[].concat([
        this._text_1,
        this._appEl_2,
        this._text_3
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'scroll',this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._ScrollerComponent_0_4.scroll.subscribe(this.eventHandler(this._handle_scroll_0_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._anchor_2,
      this._text_3
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (2 === requestNodeIndex))) { return this._TemplateRef_2_5; }
    if (((token === import19.NgFor) && (2 === requestNodeIndex))) { return this._NgFor_2_6; }
    if (((token === import18.ScrollerComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._ScrollerComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const currVal_1:any = this.parent.context.scrollbarV;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._ScrollerComponent_0_4.scrollbarV = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.scrollbarH;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._ScrollerComponent_0_4.scrollbarH = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.parent.context.scrollHeight;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._ScrollerComponent_0_4.scrollHeight = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.parent.context.columnGroupWidths.total;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._ScrollerComponent_0_4.scrollWidth = currVal_4;
      this._expr_4 = currVal_4;
    }
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ScrollerComponent_0_4.ngOnInit(); }
    changes = (null as any);
    const currVal_7:any = this.parent.context.temp;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._NgFor_2_6.ngForOf = currVal_7;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_7,currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.parent.context.rowTrackingFn;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._NgFor_2_6.ngForTrackBy = currVal_8;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForTrackBy'] = new import7.SimpleChange(this._expr_8,currVal_8);
      this._expr_8 = currVal_8;
    }
    if ((changes !== (null as any))) { this._NgFor_2_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_2_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_5:any = this._ScrollerComponent_0_4.scrollHeight;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementStyle(this._el_0,'height',((this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_5) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_5).toString() + 'px')));
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._ScrollerComponent_0_4.scrollWidth;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_6) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_6).toString() + 'px')));
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  dirtyParentQueriesInternal():void {
    (<_View_DataTableBodyComponent0>this.parent)._viewQuery_ScrollerComponent_0.setDirty();
  }
  destroyInternal():void {
    this._ScrollerComponent_0_4.ngOnDestroy();
  }
  private _handle_scroll_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onBodyScroll($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DataTableBodyComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DataTableBodyComponent2(viewUtils,parentInjector,declarationEl);
}
class _View_DataTableBodyComponent3 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _NgStyle_0_4:import23.NgStyle;
  _DataTableRowWrapperComponent_0_5:import24.DataTableRowWrapperComponent;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import2.AppElement;
  _DataTableBodyRowComponent_2_4:import25.DataTableBodyRowComponent;
  _text_3:any;
  _text_4:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent3,renderType_DataTableBodyComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'datatable-row-wrapper',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable-row-wrapper');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import26.viewFactory_DataTableRowWrapperComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._NgStyle_0_4 = new import23.NgStyle(this.parent.parent.parentInjector.get(import27.KeyValueDiffers),new import21.ElementRef(this._el_0),this.renderer);
    this._DataTableRowWrapperComponent_0_5 = new import24.DataTableRowWrapperComponent();
    this._appEl_0.initComponent(this._DataTableRowWrapperComponent_0_5,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n          ',(null as any));
    this._el_2 = this.renderer.createElement((null as any),'datatable-body-row',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','datatable-body-row');
    this.renderer.setElementAttribute(this._el_2,'tabindex','-1');
    this._appEl_2 = new import2.AppElement(2,0,this,this._el_2);
    var compView_2:any = import28.viewFactory_DataTableBodyRowComponent0(this.viewUtils,this.injector(2),this._appEl_2);
    this._DataTableBodyRowComponent_2_4 = new import25.DataTableBodyRowComponent(new import21.ElementRef(this._el_2));
    this._appEl_2.initComponent(this._DataTableBodyRowComponent_2_4,[],compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n          ',(null as any));
    compView_2.create(this._DataTableBodyRowComponent_2_4,[],(null as any));
    this._text_4 = this.renderer.createText((null as any),'\n        ',(null as any));
      compView_0.create(this._DataTableRowWrapperComponent_0_5,[[].concat([
        this._text_1,
        this._el_2,
        this._text_4
      ]
    )],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'rowContextmenu',this.eventHandler(this._handle_rowContextmenu_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'contextmenu',this.eventHandler(this._handle_contextmenu_0_1.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._DataTableRowWrapperComponent_0_5.rowContextmenu.subscribe(this.eventHandler(this._handle_rowContextmenu_0_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_2,'activate',this.eventHandler(this._handle_activate_2_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_2,'keydown',this.eventHandler(this._handle_keydown_2_1.bind(this)));
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    const subscription_1:any = this._DataTableBodyRowComponent_2_4.activate.subscribe(this.eventHandler(this._handle_activate_2_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import25.DataTableBodyRowComponent) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._DataTableBodyRowComponent_2_4; }
    if (((token === import23.NgStyle) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._NgStyle_0_4; }
    if (((token === import24.DataTableRowWrapperComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 4)))) { return this._DataTableRowWrapperComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_2:any = this.parent.parent.context.getRowsStyles(this.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgStyle_0_4.ngStyle = currVal_2;
      this._expr_2 = currVal_2;
    }
    if (!throwOnChange) { this._NgStyle_0_4.ngDoCheck(); }
    const currVal_3:any = this.parent.parent.context.rowDetailTemplate;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._DataTableRowWrapperComponent_0_5.rowDetailTemplate = currVal_3;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.parent.parent.context.detailRowHeight;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._DataTableRowWrapperComponent_0_5.detailRowHeight = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = (this.context.$implicit.$$expanded === 1);
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._DataTableRowWrapperComponent_0_5.expanded = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._DataTableRowWrapperComponent_0_5.row = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_9:any = this.parent.parent.context.columns;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._DataTableBodyRowComponent_2_4.columns = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.parent.parent.context.innerWidth;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._DataTableBodyRowComponent_2_4.innerWidth = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.$implicit;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._DataTableBodyRowComponent_2_4.row = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.parent.parent.context.offsetX;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._DataTableBodyRowComponent_2_4.offsetX = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.parent.parent.context.rowHeight;
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._DataTableBodyRowComponent_2_4.rowHeight = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = (<_View_DataTableBodyComponent0>this.parent.parent)._DataTableSelectionComponent_1_4.getRowSelected(this.context.$implicit);
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._DataTableBodyRowComponent_2_4.isSelected = currVal_14;
      this._expr_14 = currVal_14;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_15:any = this._DataTableBodyRowComponent_2_4.rowHeight;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementStyle(this._el_2,'height',((this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_15) == (null as any))? (null as any): (this.viewUtils.sanitizer.sanitize(import8.SecurityContext.STYLE,currVal_15).toString() + 'px')));
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._DataTableBodyRowComponent_2_4.isSelected;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_2,'active',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._DataTableBodyRowComponent_2_4.isEvenRow;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_2,'datatable-row-even',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._DataTableBodyRowComponent_2_4.isOddRow;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_2,'datatable-row-odd',currVal_18);
      this._expr_18 = currVal_18;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_rowContextmenu_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.parent.context.rowContextmenu.emit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_contextmenu_0_1($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DataTableRowWrapperComponent_0_5.onContextmenu($event)) !== false);
    return (true && pd_0);
  }
  private _handle_activate_2_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(<_View_DataTableBodyComponent0>this.parent.parent)._DataTableSelectionComponent_1_4.onActivate($event,this.context.index)) !== false);
    return (true && pd_0);
  }
  private _handle_keydown_2_1($event:any):boolean {
    this._appEl_2.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DataTableBodyRowComponent_2_4.onKeyDown($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DataTableBodyComponent3(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DataTableBodyComponent3(viewUtils,parentInjector,declarationEl);
}
class _View_DataTableBodyComponent4 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableBodyComponent4,renderType_DataTableBodyComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','empty-row');
    this._text_1 = this.renderer.createText(this._el_0,'\n      ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this.parent.context.emptyMessage;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_0,'innerHTML',this.viewUtils.sanitizer.sanitize(import8.SecurityContext.HTML,currVal_0));
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_DataTableBodyComponent4(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DataTableBodyComponent4(viewUtils,parentInjector,declarationEl);
}