/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../../src/components/body/selection.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/core/src/metadata/view';
import * as import9 from '@angular/core/src/linker/component_factory';
var renderType_DataTableSelectionComponent_Host:import0.RenderComponentType = (null as any);
class _View_DataTableSelectionComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DataTableSelectionComponent_0_4:import3.DataTableSelectionComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableSelectionComponent_Host0,renderType_DataTableSelectionComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('datatable-selection',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DataTableSelectionComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DataTableSelectionComponent_0_4 = new import3.DataTableSelectionComponent();
    this._appEl_0.initComponent(this._DataTableSelectionComponent_0_4,[],compView_0);
    compView_0.create(this._DataTableSelectionComponent_0_4,this.projectableNodes,(null as any));
    this.init([].concat([this._el_0]),[this._el_0],[],[]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.DataTableSelectionComponent) && (0 === requestNodeIndex))) { return this._DataTableSelectionComponent_0_4; }
    return notFoundResult;
  }
}
function viewFactory_DataTableSelectionComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_DataTableSelectionComponent_Host === (null as any))) { (renderType_DataTableSelectionComponent_Host = viewUtils.createRenderComponentType('',0,import8.ViewEncapsulation.None,[],{})); }
  return new _View_DataTableSelectionComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DataTableSelectionComponentNgFactory:import9.ComponentFactory<import3.DataTableSelectionComponent> = new import9.ComponentFactory<import3.DataTableSelectionComponent>('datatable-selection',viewFactory_DataTableSelectionComponent_Host0,import3.DataTableSelectionComponent);
const styles_DataTableSelectionComponent:any[] = [];
var renderType_DataTableSelectionComponent:import0.RenderComponentType = (null as any);
class _View_DataTableSelectionComponent0 extends import1.AppView<import3.DataTableSelectionComponent> {
  _text_0:any;
  _text_1:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_DataTableSelectionComponent0,renderType_DataTableSelectionComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this.renderer.projectNodes(parentRenderNode,import4.flattenNestedViewRenderNodes(this.projectableNodes[0]));
    this._text_1 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    this.init([],[
      this._text_0,
      this._text_1
    ]
    ,[],[]);
    return (null as any);
  }
}
export function viewFactory_DataTableSelectionComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.DataTableSelectionComponent> {
  if ((renderType_DataTableSelectionComponent === (null as any))) { (renderType_DataTableSelectionComponent = viewUtils.createRenderComponentType('',1,import8.ViewEncapsulation.None,styles_DataTableSelectionComponent,{})); }
  return new _View_DataTableSelectionComponent0(viewUtils,parentInjector,declarationEl);
}