/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../src/components/datatable.component';
import * as import4 from '@angular/core/src/linker/query_list';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/core/src/linker/element_ref';
import * as import10 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from '../../../src/directives/visibility.directive';
import * as import14 from '@angular/common/src/directives/ng_if';
import * as import15 from '../../../src/components/body/body.component';
import * as import16 from '@angular/core/src/zone/ng_zone';
import * as import17 from '@angular/core/src/linker/template_ref';
import * as import18 from './body/body.component.ngfactory';
import * as import19 from '@angular/core/src/security';
import * as import20 from '../../../src/components/header/header.component';
import * as import21 from './header/header.component.ngfactory';
import * as import22 from '../../../src/components/footer/footer.component';
import * as import23 from './footer/footer.component.ngfactory';
var renderType_DatatableComponent_Host:import0.RenderComponentType = (null as any);
class _View_DatatableComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DatatableComponent_0_4:import3.DatatableComponent;
  _query_DataTableColumnDirective_0_0:import4.QueryList<any>;
  _query_DatatableRowDetailDirective_0_1:import4.QueryList<any>;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_DatatableComponent_Host0,renderType_DatatableComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('ngx-datatable',rootSelector,(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_DatatableComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DatatableComponent_0_4 = new import3.DatatableComponent(new import9.ElementRef(this._el_0),this.parentInjector.get(import10.KeyValueDiffers));
    this._query_DataTableColumnDirective_0_0 = new import4.QueryList<any>();
    this._query_DatatableRowDetailDirective_0_1 = new import4.QueryList<any>();
    this._appEl_0.initComponent(this._DatatableComponent_0_4,[],compView_0);
    this._query_DatatableRowDetailDirective_0_1.reset([]);
    this._DatatableComponent_0_4.rowDetailTemplateChild = this._query_DatatableRowDetailDirective_0_1.first;
    compView_0.create(this._DatatableComponent_0_4,this.projectableNodes,(null as any));
    var disposable_0:Function = this.renderer.listenGlobal('window','resize',this.eventHandler(this._handle_resize_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    const subscription_0:any = this._DatatableComponent_0_4.resize.subscribe(this.eventHandler(this._handle_resize_0_0.bind(this)));
    this.init([].concat([this._el_0]),[this._el_0],[disposable_0],[subscription_0]);
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.DatatableComponent) && (0 === requestNodeIndex))) { return this._DatatableComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._DatatableComponent_0_4.ngOnInit(); }
    if (!throwOnChange) { this._DatatableComponent_0_4.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) { if (this._query_DataTableColumnDirective_0_0.dirty) {
      this._query_DataTableColumnDirective_0_0.reset([]);
      this._DatatableComponent_0_4.columnTemplates = this._query_DataTableColumnDirective_0_0;
      this._query_DataTableColumnDirective_0_0.notifyOnChanges();
    } }
    const currVal_1:any = this._DatatableComponent_0_4.isFixedHeader;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'fixed-header',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._DatatableComponent_0_4.isFixedRow;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_0,'fixed-row',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._DatatableComponent_0_4.isVertScroll;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'scroll-vertical',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._DatatableComponent_0_4.isHorScroll;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'scroll-horz',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._DatatableComponent_0_4.isSelectable;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'selectable',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._DatatableComponent_0_4.isCheckboxSelection;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'checkbox-selection',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._DatatableComponent_0_4.isCellSelection;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'cell-selection',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._DatatableComponent_0_4.isSingleSelection;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'single-selection',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._DatatableComponent_0_4.isMultiSelection;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_0,'multi-selection',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._DatatableComponent_0_4.isMultiClickSelection;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_0,'multi-click-selection',currVal_10);
      this._expr_10 = currVal_10;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._DatatableComponent_0_4.ngAfterViewInit(); } }
  }
  private _handle_resize_0_0($event:any):boolean {
    this._appEl_0.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DatatableComponent_0_4.onWindowResize()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DatatableComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_DatatableComponent_Host === (null as any))) { (renderType_DatatableComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,[],{})); }
  return new _View_DatatableComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const DatatableComponentNgFactory:import12.ComponentFactory<import3.DatatableComponent> = new import12.ComponentFactory<import3.DatatableComponent>('ngx-datatable',viewFactory_DatatableComponent_Host0,import3.DatatableComponent);
const styles_DatatableComponent:any[] = [];
var renderType_DatatableComponent:import0.RenderComponentType = (null as any);
class _View_DatatableComponent0 extends import1.AppView<import3.DatatableComponent> {
  _viewQuery_DataTableBodyComponent_0:import4.QueryList<any>;
  _text_0:any;
  _el_1:any;
  _VisibilityDirective_1_3:import13.VisibilityDirective;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import14.NgIf;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _DataTableBodyComponent_5_4:import15.DataTableBodyComponent;
  _text_6:any;
  _text_7:any;
  _anchor_8:any;
  /*private*/ _appEl_8:import2.AppElement;
  _TemplateRef_8_5:any;
  _NgIf_8_6:import14.NgIf;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_31:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_DatatableComponent0,renderType_DatatableComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._viewQuery_DataTableBodyComponent_0 = new import4.QueryList<any>();
    this._text_0 = this.renderer.createText(parentRenderNode,'\n    ',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_1,'visibility-observer','');
    this._VisibilityDirective_1_3 = new import13.VisibilityDirective(new import9.ElementRef(this._el_1),this.parentInjector.get(import16.NgZone));
    this._text_2 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_3 = new import2.AppElement(3,1,this,this._anchor_3);
    this._TemplateRef_3_5 = new import17.TemplateRef_(this._appEl_3,viewFactory_DatatableComponent1);
    this._NgIf_3_6 = new import14.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_1,'datatable-body',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','datatable-body');
    this._appEl_5 = new import2.AppElement(5,1,this,this._el_5);
    var compView_5:any = import18.viewFactory_DataTableBodyComponent0(this.viewUtils,this.injector(5),this._appEl_5);
    this._DataTableBodyComponent_5_4 = new import15.DataTableBodyComponent();
    this._appEl_5.initComponent(this._DataTableBodyComponent_5_4,[],compView_5);
    this._text_6 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_5.create(this._DataTableBodyComponent_5_4,[],(null as any));
    this._text_7 = this.renderer.createText(this._el_1,'\n      ',(null as any));
    this._anchor_8 = this.renderer.createTemplateAnchor(this._el_1,(null as any));
    this._appEl_8 = new import2.AppElement(8,1,this,this._anchor_8);
    this._TemplateRef_8_5 = new import17.TemplateRef_(this._appEl_8,viewFactory_DatatableComponent2);
    this._NgIf_8_6 = new import14.NgIf(this._appEl_8.vcRef,this._TemplateRef_8_5);
    this._text_9 = this.renderer.createText(this._el_1,'\n    ',(null as any));
    this._text_10 = this.renderer.createText(parentRenderNode,'\n  ',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_1,'visible',this.eventHandler(this._handle_visible_1_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    const subscription_0:any = this._VisibilityDirective_1_3.visible.subscribe(this.eventHandler(this._handle_visible_1_0.bind(this)));
    this._expr_2 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_5,'page',this.eventHandler(this._handle_page_5_0.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_5,'activate',this.eventHandler(this._handle_activate_5_1.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_5,'rowContextmenu',this.eventHandler(this._handle_rowContextmenu_5_2.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_5,'select',this.eventHandler(this._handle_select_5_3.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_5,'detailToggle',this.eventHandler(this._handle_detailToggle_5_4.bind(this)));
    var disposable_6:Function = this.renderer.listen(this._el_5,'scroll',this.eventHandler(this._handle_scroll_5_5.bind(this)));
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_25 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    this._expr_28 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    const subscription_1:any = this._DataTableBodyComponent_5_4.scroll.subscribe(this.eventHandler(this._handle_scroll_5_5.bind(this)));
    const subscription_2:any = this._DataTableBodyComponent_5_4.page.subscribe(this.eventHandler(this._handle_page_5_0.bind(this)));
    const subscription_3:any = this._DataTableBodyComponent_5_4.activate.subscribe(this.eventHandler(this._handle_activate_5_1.bind(this)));
    const subscription_4:any = this._DataTableBodyComponent_5_4.select.subscribe(this.eventHandler(this._handle_select_5_3.bind(this)));
    const subscription_5:any = this._DataTableBodyComponent_5_4.detailToggle.subscribe(this.eventHandler(this._handle_detailToggle_5_4.bind(this)));
    const subscription_6:any = this._DataTableBodyComponent_5_4.rowContextmenu.subscribe(this.eventHandler(this._handle_rowContextmenu_5_2.bind(this)));
    this._expr_31 = import8.UNINITIALIZED;
    this._viewQuery_DataTableBodyComponent_0.reset([this._DataTableBodyComponent_5_4]);
    this.context.bodyComponent = this._viewQuery_DataTableBodyComponent_0.first;
    this.init([],[
      this._text_0,
      this._el_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._anchor_8,
      this._text_9,
      this._text_10
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3,
      subscription_4,
      subscription_5,
      subscription_6
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import17.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import14.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import15.DataTableBodyComponent) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._DataTableBodyComponent_5_4; }
    if (((token === import17.TemplateRef) && (8 === requestNodeIndex))) { return this._TemplateRef_8_5; }
    if (((token === import14.NgIf) && (8 === requestNodeIndex))) { return this._NgIf_8_6; }
    if (((token === import13.VisibilityDirective) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._VisibilityDirective_1_3; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._VisibilityDirective_1_3.ngOnInit(); }
    const currVal_2:any = this.context.headerHeight;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_3_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    const currVal_9:any = this.context.scrollbarV;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._DataTableBodyComponent_5_4.scrollbarV = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.context.scrollbarH;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._DataTableBodyComponent_5_4.scrollbarH = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.context.loadingIndicator;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._DataTableBodyComponent_5_4.loadingIndicator = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.context.rowHeight;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._DataTableBodyComponent_5_4.rowHeight = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.context.offsetX;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._DataTableBodyComponent_5_4.offsetX = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this.context.detailRowHeight;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._DataTableBodyComponent_5_4.detailRowHeight = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.context.messages.emptyMessage;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._DataTableBodyComponent_5_4.emptyMessage = currVal_15;
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this.context.selectionType;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._DataTableBodyComponent_5_4.selectionType = currVal_16;
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this.context.selected;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this._DataTableBodyComponent_5_4.selected = currVal_17;
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this.context.rowIdentity;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this._DataTableBodyComponent_5_4.rowIdentity = currVal_18;
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this.context.rowDetailTemplate;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this._DataTableBodyComponent_5_4.rowDetailTemplate = currVal_19;
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this.context.selectCheck;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this._DataTableBodyComponent_5_4.selectCheck = currVal_20;
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this.context.trackByProp;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this._DataTableBodyComponent_5_4.trackByProp = currVal_21;
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this.context.pageSize;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this._DataTableBodyComponent_5_4.pageSize = currVal_22;
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this.context.rows;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this._DataTableBodyComponent_5_4.rows = currVal_23;
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this.context.columns;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this._DataTableBodyComponent_5_4.columns = currVal_24;
      this._expr_24 = currVal_24;
    }
    const currVal_25:any = this.context.offset;
    if (import5.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this._DataTableBodyComponent_5_4.offset = currVal_25;
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this.context.rowCount;
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this._DataTableBodyComponent_5_4.rowCount = currVal_26;
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this.context.innerWidth;
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this._DataTableBodyComponent_5_4.innerWidth = currVal_27;
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this.context.bodyHeight;
    if (import5.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this._DataTableBodyComponent_5_4.bodyHeight = currVal_28;
      this._expr_28 = currVal_28;
    }
    const currVal_31:any = this.context.footerHeight;
    if (import5.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this._NgIf_8_6.ngIf = currVal_31;
      this._expr_31 = currVal_31;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._VisibilityDirective_1_3.isVisible;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_1,'visible',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_29:any = this._DataTableBodyComponent_5_4.bodyWidth;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementStyle(this._el_5,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_29) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_29).toString()));
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._DataTableBodyComponent_5_4.bodyHeight;
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementStyle(this._el_5,'height',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_30) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_30).toString()));
      this._expr_30 = currVal_30;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._VisibilityDirective_1_3.ngOnDestroy();
  }
  private _handle_visible_1_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.recalculate()) !== false);
    return (true && pd_0);
  }
  private _handle_page_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onBodyPage($event)) !== false);
    return (true && pd_0);
  }
  private _handle_activate_5_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.activate.emit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_rowContextmenu_5_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.rowContextmenu.emit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_select_5_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onBodySelect($event)) !== false);
    return (true && pd_0);
  }
  private _handle_detailToggle_5_4($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.detailToggle.emit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_scroll_5_5($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.onBodyScroll($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_DatatableComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import3.DatatableComponent> {
  if ((renderType_DatatableComponent === (null as any))) { (renderType_DatatableComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,styles_DatatableComponent,{})); }
  return new _View_DatatableComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_DatatableComponent1 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DataTableHeaderComponent_0_4:import20.DataTableHeaderComponent;
  _text_1:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_DatatableComponent1,renderType_DatatableComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'datatable-header',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable-header');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import21.viewFactory_DataTableHeaderComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DataTableHeaderComponent_0_4 = new import20.DataTableHeaderComponent();
    this._appEl_0.initComponent(this._DataTableHeaderComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_0.create(this._DataTableHeaderComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'sort',this.eventHandler(this._handle_sort_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'resize',this.eventHandler(this._handle_resize_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reorder',this.eventHandler(this._handle_reorder_0_2.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_0,'select',this.eventHandler(this._handle_select_0_3.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    this._expr_10 = import8.UNINITIALIZED;
    this._expr_11 = import8.UNINITIALIZED;
    this._expr_12 = import8.UNINITIALIZED;
    this._expr_13 = import8.UNINITIALIZED;
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    const subscription_0:any = this._DataTableHeaderComponent_0_4.sort.subscribe(this.eventHandler(this._handle_sort_0_0.bind(this)));
    const subscription_1:any = this._DataTableHeaderComponent_0_4.reorder.subscribe(this.eventHandler(this._handle_reorder_0_2.bind(this)));
    const subscription_2:any = this._DataTableHeaderComponent_0_4.resize.subscribe(this.eventHandler(this._handle_resize_0_1.bind(this)));
    const subscription_3:any = this._DataTableHeaderComponent_0_4.select.subscribe(this.eventHandler(this._handle_select_0_3.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import20.DataTableHeaderComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._DataTableHeaderComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_4:any = this.parent.context.cssClasses.sortAscending;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._DataTableHeaderComponent_0_4.sortAscendingIcon = currVal_4;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.parent.context.cssClasses.sortDescending;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._DataTableHeaderComponent_0_4.sortDescendingIcon = currVal_5;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.parent.context.scrollbarH;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._DataTableHeaderComponent_0_4.scrollbarH = currVal_6;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.parent.context.innerWidth;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._DataTableHeaderComponent_0_4.innerWidth = currVal_7;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.parent.context.offsetX;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._DataTableHeaderComponent_0_4.offsetX = currVal_8;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.parent.context.sorts;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._DataTableHeaderComponent_0_4.sorts = currVal_9;
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this.parent.context.sortType;
    if (import5.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this._DataTableHeaderComponent_0_4.sortType = currVal_10;
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this.parent.context.allRowsSelected;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this._DataTableHeaderComponent_0_4.allRowsSelected = currVal_11;
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this.parent.context.selectionType;
    if (import5.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this._DataTableHeaderComponent_0_4.selectionType = currVal_12;
      this._expr_12 = currVal_12;
    }
    const currVal_13:any = this.parent.context.reorderable;
    if (import5.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._DataTableHeaderComponent_0_4.reorderable = currVal_13;
      this._expr_13 = currVal_13;
    }
    const currVal_14:any = this.parent.context.headerHeight;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this._DataTableHeaderComponent_0_4.headerHeight = currVal_14;
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this.parent.context.columns;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._DataTableHeaderComponent_0_4.columns = currVal_15;
      this._expr_15 = currVal_15;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_16:any = this._DataTableHeaderComponent_0_4.headerHeight;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementStyle(this._el_0,'height',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_16) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_16).toString()));
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._DataTableHeaderComponent_0_4.headerWidth;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementStyle(this._el_0,'width',((this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_17) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import19.SecurityContext.STYLE,currVal_17).toString()));
      this._expr_17 = currVal_17;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_sort_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onColumnSort($event)) !== false);
    return (true && pd_0);
  }
  private _handle_resize_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onColumnResize($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reorder_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onColumnReorder($event)) !== false);
    return (true && pd_0);
  }
  private _handle_select_0_3($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onHeaderSelect($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DatatableComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DatatableComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_DatatableComponent2 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _DataTableFooterComponent_0_4:import22.DataTableFooterComponent;
  _text_1:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_DatatableComponent2,renderType_DatatableComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'datatable-footer',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','datatable-footer');
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = import23.viewFactory_DataTableFooterComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._DataTableFooterComponent_0_4 = new import22.DataTableFooterComponent();
    this._appEl_0.initComponent(this._DataTableFooterComponent_0_4,[],compView_0);
    this._text_1 = this.renderer.createText((null as any),'\n      ',(null as any));
    compView_0.create(this._DataTableFooterComponent_0_4,[],(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'page',this.eventHandler(this._handle_page_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    const subscription_0:any = this._DataTableFooterComponent_0_4.page.subscribe(this.eventHandler(this._handle_page_0_0.bind(this)));
    this.init([].concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import22.DataTableFooterComponent) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 1)))) { return this._DataTableFooterComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changed:boolean = true;
    changed = false;
    const currVal_1:any = this.parent.context.footerHeight;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._DataTableFooterComponent_0_4.footerHeight = currVal_1;
      changed = true;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.parent.context.rowCount;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._DataTableFooterComponent_0_4.rowCount = currVal_2;
      changed = true;
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this.parent.context.pageSize;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this._DataTableFooterComponent_0_4.pageSize = currVal_3;
      changed = true;
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this.parent.context.offset;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this._DataTableFooterComponent_0_4.offset = currVal_4;
      changed = true;
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this.parent.context.cssClasses.pagerLeftArrow;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this._DataTableFooterComponent_0_4.pagerLeftArrowIcon = currVal_5;
      changed = true;
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this.parent.context.cssClasses.pagerRightArrow;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this._DataTableFooterComponent_0_4.pagerRightArrowIcon = currVal_6;
      changed = true;
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this.parent.context.cssClasses.pagerPrevious;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this._DataTableFooterComponent_0_4.pagerPreviousIcon = currVal_7;
      changed = true;
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this.parent.context.cssClasses.pagerNext;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this._DataTableFooterComponent_0_4.pagerNextIcon = currVal_8;
      changed = true;
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this.parent.context.messages.totalMessage;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this._DataTableFooterComponent_0_4.totalMessage = currVal_9;
      changed = true;
      this._expr_9 = currVal_9;
    }
    if (changed) { this._appEl_0.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_page_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onFooterPage($event)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_DatatableComponent2(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_DatatableComponent2(viewUtils,parentInjector,declarationEl);
}